# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d28cf7fbcc733f92b95d5000bc24fdb836565d57197f49aec98d8ac0c9ee081f57738e10f4a2804651b5b0ba608ae4597f73cf0fad94e0e42975289346dab4fd

test:
  secret_key_base: bad624d6390f92723a56f239c89e0947a17e0364c43344ba3d8c88f8460bee9ff737280b3cf96a5a6afef8c3c6810b183c24cd166d0aaae5b41fdc328ebf326e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
